management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  mail:
    host: smtp.qq.com
    username: 455374274@qq.com
    password: jtdousvrbuaobhgh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          to: hswu@ai-kang.cn
          from: 455374274@qq.com


