server:
  port: 8000
spring:
  application:
    name: admin-server
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: pwd666

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    metadata-map:
      user.name: admin
      user.password: pwd666
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:6080/eureka/


logging:
  file: G:/mylog/api-admin.log
